#!/bin/sh

# oh my zsh
curl https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh


# antigen
cd ~ && git clone https://github.com/zsh-users/antigen.git .antigen

# brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install node
brew install pt
brew install hub
brew install wget
brew tap neovim/homebrew-neovim
brew install neovim


brew cask install google-chrome


git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install


# links
ln -sf ~/.dotfiles/editorconfig      ~/editorconfig

ln -sf ~/.dotfiles/git/gitconfig     ~/.gitconfig
ln -sf ~/.dotfiles/git/gitignore     ~/.gitignore

ln -sf ~/.dotfiles/vim/gvimrc        ~/.gvimrc
ln -sf ~/.dotfiles/vim/vimrc         ~/.vimrc

ln -sf ~/.dotfiles/jshintrc          ~/.jshintrc

ln -sf ~/.dotfiles/ptignore          ~/.ptignore

ln -sf ~/.dotfiles/zsh/zprofile      ~/.zprofile
ln -sf ~/.dotfiles/zsh/zshrc         ~/.zshrc

ln -sf ~/.dotfiles/slate.js         ~/.slate.js

# vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Downloads
curl https://pqrs.org/osx/karabiner/files/Karabiner-10.6.0.dmg > ~/Downloads/Karabiner.dmg
wget -O ~/Downloads/iTerm2.zip https://iterm2.com/downloads/stable/iTerm2_v2_0.zip
wget -O ~/Downloads/KeepingYouAwake-1.2.1.zip https://github.com/newmarcel/KeepingYouAwake/releases/download/1.2.1/KeepingYouAwake-1.2.1.zip


# install node
curl -L http://git.io/n-install | bash
n latest

# node_modules
npm install serve -g
npm install -g yo
npm install --global dark-mode
npm install -g gitgoodies
npm install -g cut-release
