set nocompatible
source ~/.dotfiles/vim/plugins.vim
source ~/.dotfiles/vim/functions.vim
source ~/.dotfiles/vim/settings.vim
source ~/.dotfiles/vim/mappings.vim
source ~/.dotfiles/vim/filetypes.vim
source ~/.dotfiles/vim/abbreviations.vim
source ~/.dotfiles/vim/terminal.vim
source ~/.dotfiles/vim/work-git-ignored.vim
source ~/.dotfiles/vim/elm.vim
source ~/.dotfiles/vim/haskell.vim
source ~/.dotfiles/vim/markdown.vim
source ~/.dotfiles/vim/ruby.vim
source ~/.dotfiles/vim/reason.vim
" source ~/.dotfiles/vim/focus-dark.vim
" source ~/.dotfiles/vim/focus-light.vim

if filereadable('.local.vim')
  so .local.vim
endif
