ZSH=$HOME/.oh-my-zsh

ZSH_THEME="pure"

plugins=(git node npm bower gem gitfast vundle )

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export ECLIPSE_HOME=/Applications/eclipse/
export PATH=$PATH:bin:./node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/home/$USER/.gem/ruby/1.8/bin:/opt/nginx/sbin:/home/$USER/bin/adt-bundle-linux-x86_64-20140702/sdk/tools:/home/$USER/bin/adt-bundle-linux-x86_64-20140702/sdk/platform-tools:/home/$USER/bin:/home/$USER/.bash_it/plugins/available/todo:~/bin/dart/dart-sdk/bin:~/.dotfiles/bin:/Applications/eclipse
export PATH=/opt/local/bin:/usr/local/sbin:/opt/local/sbin:$PATH
export TERM='xterm-256color'

# EDITOR
########
export EDITOR='nvim'

# ALIASES
#########

# Source files
alias soz="source ~/.zshrc"
alias sov="source ~/.vimrc"

# Git
alias gg='noglob gg'
alias ga="gg a"
alias gaa="git add ."
alias gac="git commit -a"
alias gd="git difftool"
alias gs="git status;gg s"
alias gp="git push"
alias gl="git pull --rebase"
alias gerrit-hook="scp -p -P 29418 chermann@git.tocco.ch:hooks/commit-msg .git/hooks/"
function vn () {
    vim `git status | grep new | awk '{print $3}'`
}

function vm () {
    vim `git status | grep modified | awk '{print $2}'`
}

function vc () {
    vim `git unpushed | awk '{print $2}'`
}


function lint_cloud () {
    eslint --rulesdir ~/cloud/eslintrules -c ~/cloud/.eslintrc --ignore-path ~/cloud/.eslintignore $1
}

function lint_new () {
    eslint --rulesdir ./eslintrules -c .eslintrc --ignore-path .eslintignore `git status | grep new | awk '{print $2}'`
}

function lint_modified () {
    echo Linting `git status | grep modified | awk '{print $2}'`
    eslint --rulesdir ./eslintrules -c .eslintrc --ignore-path .eslintignore `git status | grep modified | awk '{print $2}'`
}

function lint_unpushed () {
    eslint --rulesdir ./eslintrules -c .eslintrc --ignore-path .eslintignore `git unpushed | awk '{print $2}'`
}

function lint () {
    lint_new
    lint_modified
}

function githubpr() {
    git fetch origin pull/$1/head:$2
    git checkout $2
}

# NPM
alias n="npm "
alias nr="npm run "
alias ni="npm install "
alias np="npm publish "
alias nt="npm test"
alias nu="npm update"
alias ns="npm run-script "

# Svn
alias ss="svn status"
alias sa="svn status | grep '?' | sed 's/^.* /svn add /' | zsh"
alias sc="svn commit"
alias sl="svn update"
alias scl="svn checkout"

# Vim
alias mvim='open -a MacVim'
alias vo="nvim -u NONE -N"
alias vi="nvim"
alias v="nvim"
alias v.="nvim ."
alias m="mvim"

# Compass
alias cc="compass compile"
alias cw="compass watch"

# Grulp
alias gr="grulp"

# Applications
alias c="open -a Google\ Chrome"
alias canary="open -a /Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --args --disable-web-security"
alias st="open -a SourceTree"

function op() {
    chrome-cli open http://127.0.0.1/$1
}

# List
alias l="ls -a"

# VID (very important directories)
alias cdd="cd ~/.dotfiles"
alias dv="cd ~/.dotfiles;vim;cd -;" # edit dotfiles, and go back were you came from
alias dl="d;git pull;"
alias s="cd ~/src"

alias sencha="/home/${USER}/bin/Sencha/Cmd/5.0.0.160/sencha";
alias sen="/home/${USER}/bin/Sencha/Cmd/5.0.0.160/sencha";
alias senw="sen app watch";
alias senb="sen app build";

# DEPRECATED
alias ll="echo use l"
alias gall="echo use ga"
alias gst="echo use gs"

# PHP SERVER
alias phpserver="php -S localhost:8000 -c ~/.dotfiles/php.ini"

# TMUX
alias tmux="tmux -u"
alias ta="tmux -2 attach-session -t"
alias tn="tmux -2 new-session -s"
alias ts="tmux switch-client -t"
alias ms="mux start"

alias nw="/Applications/node-webkit.app/Contents/MacOS/node-webkit"

alias fc='noglob fc'
alias find='noglob find'
alias ftp='noglob ftp'
alias history='noglob history'
alias locate='noglob locate'
alias rake='noglob rake'
alias rsync='noglob rsync'
alias scp='noglob scp'
alias sftp='noglob sftp'

#########

zstyle ':completion:*' special-dirs true

export LC_ALL=en_US.UTF-8

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_21.jdk/Contents/Home
export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=300m"


dark-mode --mode Dark

unsetopt inc_append_history
unsetopt share_history
